# Generated by Django 3.1.7 on 2021-04-01 15:49

import chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='email',
            field=models.EmailField(max_length=255, validators=[chat.validators.validate_email]),
        ),
    ]
