# Generated by Django 3.1.7 on 2021-04-02 07:23

import chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210401_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(validators=[chat.validators.validate_text]),
        ),
    ]
