# Generated by Django 3.1.7 on 2021-04-02 07:47

import chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210402_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='email',
            field=models.EmailField(max_length=255, validators=[chat.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, validators=[chat.validators.validate_text]),
        ),
    ]
