# Generated by Django 3.1.7 on 2021-04-02 07:47

import chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210402_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(validators=[chat.validators.validate_text]),
        ),
    ]
